### PR TITLE
Remove the 'onDelete' feature

### PR DESCRIPTION
**Pull request by Giska**
As it cause the process to hang in some cases and anyway it's not something to recommend. 

PR-content: https://github.com/craft-ai/content/pull/40

Connects to https://github.com/craft-ai/craft-ai/issues/474

### CODE REVIEW

**Comment by cloderic** [comment]
A little violent no? You'd like your dependencies to kil your program?

Maybe we can remove the **destroy agent on stop** feature instead.

**Comment by Giska** [comment]
There is another way to do it, we can handle it in the express side.

From the node js doc:
`SIGTERM and SIGINT have default handlers on non-Windows platforms that resets the terminal mode before exiting with code 128 + signal number. If one of these signals has a listener installed, its default behavior will be removed (Node.js will no longer exit).`

But we can remove this feature in a first time

**Comment by cloderic** [comment]
#47 is the way

**Comment by cloderic** [comment]
Need to update the readme and good

**Pull request merged**
